### PR TITLE
pt-br.po

### PR DESCRIPTION
**Pull request by JonasJF360**
Translation file of the application into Brazilian Portuguese.
(Arquivo de tradução do aplicativo pata Português Brasileiro).

### CODE REVIEW

**Comment by cardsurf** [comment]
Hi @JonasJF360.
Good job creating the translation.
This is just my private repository that I do not update too frequently.
Please commit the .po file to [cinnamon-spices-applets](https://github.com/linuxmint/cinnamon-spices-applets/tree/master/brightness-and-gamma-applet%40cardsurf/files/brightness-and-gamma-applet%40cardsurf/po) repository. It would be available to all Cinnamon users through Cinnamon Spices website and `Applets` application in Linux Mint. 
In case you need any help doing it just let me know.

**Comment by JonasJF360** [comment]
Hello, @cardsurf!

Thanks for accepting my suggestion, and as suggested I sent the same file
to the "cinnamon-spices-applets repository" and I am awaiting your
evaluation.

Unfortunately, despite having translated, I did not understand correctly
how to apply the translation in the application and would like to know if
you have any manual how to do this.
"Translated by Google Translator, sorry if something does not make sense."

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

Obrigado por aceitar minha sugestão, e, assim como sugerido eu enviei o
mesmo arquivo para o "cinnamon-spices-applets repository" e estou
aguardando sua avaliação.

Infelizmente, apesar de ter traduzido, não entendi corretamente como
aplicar a tradução no aplicativo e gostaria de saber se você tem algum
manual de como fazer isso.
"

Em qua, 3 de jul de 2019 às 10:54, cardsurf <notifications@github.com>
escreveu:

**Comment by cardsurf** [comment]
To add the translation you would need to put the .po file under the following directory of cinnamon-spices-applets repository:
https://github.com/linuxmint/cinnamon-spices-applets/tree/master/brightness-and-gamma-applet%40cardsurf/files/brightness-and-gamma-applet%40cardsurf/po


Then create a pull request on a separate branch to [cinnamon-spices-applets](https://github.com/linuxmint/cinnamon-spices-applets) repository. Once you do that it will be visible in the `Pull requests` tab for a code review. If all is good it will be merged into master.

[Here](https://github.com/linuxmint/cinnamon-spices-applets/pull/2429) is an example of pull request for adding new translation file. You can read a little more about adding translations in the [README](https://github.com/linuxmint/cinnamon-spices-applets/blob/master/README.md).

**Comment by cardsurf** [comment]
I noticed that the [pull request](https://github.com/linuxmint/cinnamon-spices-applets/pull/2473) has been merged to cinnamon-spices-applets repository. I will also merge it here so translation is in both repositories.

**Pull request merged**
